from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml

from engine.git_watcher import GitWatcher

_CONTEXT_TEMPLATE = """\
# AI_CONTEXT.md

> Auto-generated by TRACE. Keep this file current.

---

## Project

(Project details not yet configured.)

---

## Last updated

{date}
"""

# Rough budget: 1 token ≈ 4 chars; cap at 950 tokens worth of content
_MAX_PROMPT_CHARS = 3800


class DocSynthesizer:
    """Reads git changes and updates AI_CONTEXT.md via targeted section patches."""

    def __init__(
        self,
        project_path: str,
        config_path: str = "trace_config.yaml",
    ) -> None:
        self.project_path = Path(project_path).resolve()
        self.watcher = GitWatcher(project_path)

        cfg = Path(config_path)
        if not cfg.is_absolute():
            cfg = self.project_path / cfg
        with open(cfg) as f:
            self.config = yaml.safe_load(f)

    # ------------------------------------------------------------------
    # File helpers
    # ------------------------------------------------------------------

    def get_context_path(self) -> Path:
        """Return path to AI_CONTEXT.md, creating it from template if absent."""
        path = self.project_path / "AI_CONTEXT.md"
        if not path.exists():
            path.write_text(
                _CONTEXT_TEMPLATE.format(date=date.today().isoformat()),
                encoding="utf-8",
            )
        return path

    def read_context(self) -> str:
        """Return current AI_CONTEXT.md content, or '' if it does not exist."""
        path = self.project_path / "AI_CONTEXT.md"
        return path.read_text(encoding="utf-8") if path.exists() else ""

    def get_context_age_days(self) -> int | None:
        """Return the age in whole days of AI_CONTEXT.md, or None if it does not exist."""
        from datetime import datetime, timezone
        path = self.project_path / "AI_CONTEXT.md"
        if not path.exists():
            return None
        mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        return (datetime.now(tz=timezone.utc) - mtime).days

    # ------------------------------------------------------------------
    # Sync bookmark (.trace_sync)
    # ------------------------------------------------------------------

    def get_last_synced(self) -> str | None:
        """Return the hash stored in .trace_sync, or None if the file is absent."""
        sync_file = self.project_path / ".trace_sync"
        if not sync_file.exists():
            return None
        content = sync_file.read_text(encoding="utf-8").strip()
        return content or None

    def update_last_synced(self, hash: str) -> None:
        """Write hash to .trace_sync (the sync bookmark)."""
        (self.project_path / ".trace_sync").write_text(hash.strip(), encoding="utf-8")

    # ------------------------------------------------------------------
    # Drift detection
    # ------------------------------------------------------------------

    def check_drift(self, last_synced_hash: str) -> dict:
        """Compare last_synced_hash against current HEAD and report drift."""
        current_hash = self.watcher.get_last_commit().get("hash", "")

        if not current_hash or last_synced_hash == current_hash:
            return {
                "is_stale": False,
                "commits_behind": 0,
                "changed_files": [],
                "doc_relevant_changes": False,
                "last_synced_hash": last_synced_hash,
                "current_hash": current_hash,
            }

        commits = self.watcher.get_commits_since(last_synced_hash)
        changed_files = self.watcher.get_changed_files(since_hash=last_synced_hash)
        doc_relevant = any(self.watcher.is_doc_relevant(f) for f in changed_files)

        return {
            "is_stale": True,
            "commits_behind": len(commits),
            "changed_files": changed_files,
            "doc_relevant_changes": doc_relevant,
            "last_synced_hash": last_synced_hash,
            "current_hash": current_hash,
        }

    # ------------------------------------------------------------------
    # Prompt builder
    # ------------------------------------------------------------------

    def build_update_prompt(self, since_hash: str) -> str:
        """Build a concise LLM prompt summarising what changed since since_hash."""
        commits = self.watcher.get_commits_since(since_hash)

        if not commits:
            return f"No new commits since {since_hash}."

        lines: list[str] = [
            f"AI_CONTEXT.md update needed. {len(commits)} new commit(s) since {since_hash}:",
            "",
        ]

        for i, commit in enumerate(commits[:10], start=1):
            lines.append(f"[{i}] {commit['hash']} by {commit['author']}")
            lines.append(f"    Message: {commit['message']}")
            lines.append(f"    Changes: {commit['diff_summary']}")
            top_files = commit["files_changed"][:5]
            if top_files:
                lines.append(f"    Files: {', '.join(top_files)}")
                if len(commit["files_changed"]) > 5:
                    lines.append(f"    ... and {len(commit['files_changed']) - 5} more file(s)")
            lines.append("")

        if len(commits) > 10:
            lines.append(f"(+{len(commits) - 10} additional commit(s) not shown)")
            lines.append("")

        doc_relevant = [
            f
            for c in commits
            for f in c["files_changed"]
            if self.watcher.is_doc_relevant(f)
        ]
        if doc_relevant:
            unique = sorted(set(doc_relevant))[:8]
            lines.append(f"Key files modified: {', '.join(unique)}")

        prompt = "\n".join(lines)

        if len(prompt) > _MAX_PROMPT_CHARS:
            prompt = prompt[:_MAX_PROMPT_CHARS - 3] + "..."

        return prompt

    # ------------------------------------------------------------------
    # Section updater
    # ------------------------------------------------------------------

    def apply_section_update(self, section: str, new_content: str) -> bool:
        """Replace the body of a ## section in AI_CONTEXT.md with new_content.

        Returns True if the section was found and updated, False otherwise.
        Never rewrites the entire file – only the targeted section body.
        """
        context_path = self.get_context_path()
        if not context_path.exists():
            return False

        content = context_path.read_text(encoding="utf-8")
        lines = content.split("\n")

        target_heading = f"## {section}"
        start_idx = next(
            (i for i, line in enumerate(lines) if line.strip() == target_heading),
            None,
        )
        if start_idx is None:
            return False

        # Section ends at the next ## heading, --- separator, or EOF
        end_idx = len(lines)
        for i in range(start_idx + 1, len(lines)):
            if lines[i].startswith("## ") or lines[i].strip() == "---":
                end_idx = i
                break

        replacement = [lines[start_idx], ""] + new_content.strip().split("\n") + [""]
        updated = "\n".join(lines[:start_idx] + replacement + lines[end_idx:])
        context_path.write_text(updated, encoding="utf-8")
        return True
