#!/usr/bin/env bash
# Usage: ./hooks/install_hook.sh /path/to/target/project
#
# Installs the TRACE post-commit hook into a target git repository.
# The installed hook hardcodes the TRACE installation path so it works
# without any environment variable setup.

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 /path/to/target/project"
    exit 1
fi

TARGET="$(cd "$1" && pwd)"
TRACE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -d "$TARGET/.git" ]; then
    echo "Error: '$TARGET' is not a git repository"
    exit 1
fi

HOOK_DST="$TARGET/.git/hooks/post-commit"

cat > "$HOOK_DST" << HOOK
#!/usr/bin/env bash
# TRACE post-commit hook – auto-generated by install_hook.sh
# TRACE installation: $TRACE_ROOT

PROJECT_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)"
TRACE_HOME="$TRACE_ROOT"

# Auto-register project in ~/.trace/trace.db if not yet known
python3 -c "
import sys
sys.path.insert(0, '\$TRACE_HOME')
from engine.auto_register import register_if_unknown
register_if_unknown('\$PROJECT_ROOT')
" 2>/dev/null || true

# Update AI_CONTEXT.md if doc-relevant changes detected
python3 "\$TRACE_HOME/engine/hook_runner.py" "\$PROJECT_ROOT" 2>/dev/null || true
HOOK

chmod +x "$HOOK_DST"
echo "TRACE hook installed in $TARGET"

# Auto-register the project now
python3 "$TRACE_ROOT/engine/auto_register.py" "$TARGET" || true
